### ISSUE TITLE
Allow it to use npm installed clang-format

### ISSUE THREAD

**Issue by alex321** [xaverh/vscode-clang-format-provider#26] opened 2016-11-26 15:29 UTC
If I install clang-format from npm globally, I am unable to use it as it is looking for the .exe it seems. Could you allow it to use either windows or npm installed versions?

Thanks.

**Comment by xaverh** [comment] 2016-11-28 09:16
Duplicate of #19

**Closed by xaverh** 2016-11-28 09:16 UTC
